language: node_js
node_js:
  - "node"
install:
  - yarn
  - yarn add -g codecov
cache: yarn
stages:
  - lint
  - test
jobs:
  include:
    - stage: lint
      script:
        - yarn lint
    - stage: test
      script:
        - yarn test:unit && codecov