language: node_js
install:
  - yarn
cache: yarn
stages:
  - lint
  - test
jobs:
  include:
    - stage: lint
      script:
        # Run linter
        - yarn lint
    - stage: test
      script:
        # Run tests
        - yarn test:unit